DROP INDEX IF EXISTS idx_album_name;
DROP INDEX IF EXISTS idx_album_created_at;
DROP INDEX IF EXISTS idx_album_updated_at;

ALTER TABLE album DROP CONSTRAINT IF EXISTS album_timestamps_check;
ALTER TABLE album DROP CONSTRAINT IF EXISTS album_name_unique;

ALTER TABLE album ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE album ALTER COLUMN updated_at DROP DEFAULT;

ALTER TABLE album ALTER COLUMN id   TYPE VARCHAR;
ALTER TABLE album ALTER COLUMN name TYPE VARCHAR;
